# sources.yaml - Data Source Configuration for gndb populate
#
# This file defines which SFGA data sources to import.
# Default location: {ConfigDir}/gndb/sources.yaml (same directory as config.yaml)
# See: specs/001-gnverifier-db-lifecycle/sources-yaml-spec.md
#
# Usage:
#   gndb populate                 # Uses default {ConfigDir}/gndb/sources.yaml
#   gndb populate --sources 1,3,5 # Import only specific IDs
#   gndb populate --sources main  # ID < 1000 only
#   gndb populate --exclude main  # ID >= 1000 only
#   gndb populate --sources-config /path/to/custom-sources.yaml  # Edge case: custom location
#
# Configuration settings (batch_size, concurrent_jobs, logging, etc.) are in config.yaml

# ============================================================================
# Data Sources
# ============================================================================

data_sources:
  # Catalogue of Life
  - id: 1
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "Catalogue of Life"
    home_url: "https://www.catalogueoflife.org/"
    data_url: "http://www.catalogueoflife.org/DCA_Export/archive.php"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://www.catalogueoflife.org/data/taxon/{}"
    outlink_id_field: "record_id"

  # Wikispecies
  - id: 2
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "Wikispecies"
    home_url: "https://species.wikimedia.org/wiki/Main_Page"
    data_url: "http://dumps.wikimedia.org/specieswiki/latest/specieswiki-latest-pages-articles.xml.bz2"
    is_curated: true
    is_outlink_ready: true
    outlink_url: "http://species.wikimedia.org/wiki/{}"
    outlink_id_field: "canonical_full"

  # ITIS
  - id: 3
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title: "Integrated Taxonomic Information System"
    title_short: "ITIS"
    home_url: "https://www.itis.gov/"
    data_url: "https://www.itis.gov/downloads/itisMySQLTables.tar.gz"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value={}#null"
    outlink_id_field: "record_id"

  # NCBI
  - id: 4
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title: "National Center for Biotechnology Information"
    title_short: "NCBI"
    home_url: "https://www.ncbi.nlm.nih.gov/"
    data_url: "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
    is_outlink_ready: true
    outlink_url: "https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&name={}&lvl=0&srchmode=1&keep=1&unlock"
    outlink_id_field: "canonical"

  # GRIN Plant Taxonomy
  - id: 6
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title: "USDA National Plant Germplasm System"
    title_short: "GRIN Plant Taxonomy"
    home_url: "https://npgsweb.ars-grin.gov/gringlobal/taxon/abouttaxonomy"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://npgsweb.ars-grin.gov/gringlobal/taxon/taxonomydetail?id={}"
    outlink_id_field: "record_id"

  # WoRMS
  - id: 9
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "WoRMS"
    home_url: "https://marinespecies.org"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://www.marinespecies.org/aphia.php?p=taxdetails&id={}"
    outlink_id_field: "record_id"

  # EOL
  - id: 12
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "EOL"
    home_url: "https://eol.org"
    data_url: "https://eol.org/data/provider_ids.csv.gz"
    is_auto_curated: true
    is_outlink_ready: true
    outlink_url: "https://eol.org/pages/{}"
    outlink_id_field: "name_id"

  # VASCAN
  - id: 147
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "VASCAN"
    is_curated: true
    has_classification: true

  # IPNI
  - id: 167
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "IPNI"
    home_url: "https://www.ipni.org/"
    is_curated: true
    is_outlink_ready: true
    outlink_url: "https://www.ipni.org/n/{}"
    outlink_id_field: "name_id"

  # Arctos
  - id: 170
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "Arctos"
    home_url: "https://arctosdb.org/"
    is_auto_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://arctos.database.museum/name/{}"
    outlink_id_field: "canonical_full"

  # PaleoBioDB
  - id: 172
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "PaleoBioDB"
    home_url: "https://paleobiodb.org/#/"
    is_curated: true
    has_classification: true

  # iNaturalist
  - id: 180
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "iNaturalist"
    home_url: "https://inaturalist.org/"
    data_url: "https://www.inaturalist.org/taxa/inaturalist-taxonomy.dwca.zip"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://www.inaturalist.org/taxa/{}"
    outlink_id_field: "record_id"

  # World Flora Online
  - id: 196
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "World Flora Online"
    home_url: "https://worldfloraonline.org"
    description: "An Online Flora of All Known Plants"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "https://list.worldfloraonline.org/{}"
    outlink_id_field: "name_id"

  # MycoBank
  - id: 203
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "MycoBank"
    home_url: "https://www.mycobank.org"
    is_curated: true
    is_outlink_ready: true
    outlink_url: "https://www.mycobank.org/page/Name details page/{}"
    outlink_id_field: "name_id"

  # Ruhoff 1980
  - id: 206
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "Ruhoff 1980"
    home_url: "https://doi.org/10.5479/si.00810282.294"
    is_auto_curated: true

  # LPSN
  - id: 208
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "LPSN"
    home_url: "https://lpsn.dsmz.de/"
    data_url: "https://lpsn.dsmz.de/downloads"
    is_curated: true
    has_classification: true
    is_outlink_ready: true
    outlink_url: "{}"
    outlink_id_field: "local_id"

  # TAXREF
  - id: 210
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "TAXREF"
    home_url: "https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref"
    data_url: "https://ipt.gbif.fr/resource?r=taxref"
    is_curated: true
    has_classification: true

  # World Plants
  - id: 211
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "World Plants"

  # World Ferns
  - id: 212
    parent_url: http://opendata.globalnames.org/sfga/latest/
    title_short: "World Ferns"
# ============================================================================
# Template for Custom Data Sources
# ============================================================================
# Copy and customize this template for your own data sources (ID >= 1000):
#
# - id: 1000
#   parent_dir: ~/data/
#   parent_url: (an alternative to parent_dir)
#   title: "Full Title"
#   title_short: "ShortName"      # Required for display
#   description: "Detailed description"
#   home_url: "https://example.org"
#   data_url: "https://example.org/download"
#   data_source_type: "taxonomic"  # or "nomenclatural"
#   is_curated: false
#   is_auto_curated: false
#   has_classification: false
#   is_outlink_ready: false
#   outlink_url: "https://example.org/{}"
#   outlink_id_field: "record_id"
