package ioexport

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/gnames/gndb/pkg/config"
	"github.com/gnames/gndb/pkg/schema"
	"github.com/gnames/gndb/pkg/sources"
	"github.com/sfborg/sflib"
	"github.com/sfborg/sflib/pkg/sfga"
	"gopkg.in/yaml.v3"
)


// initSfga creates a fresh SFGA SQLite database in workDir and opens
// a connection to it. workDir must be empty — sflib.Create requires this.
// Fetches the SFGA schema from a remote Git repo; requires internet access.
func initSfga(workDir string) (sfga.Archive, error) {
	slog.Info("Creating SFGA database", "dir", workDir)

	arc := sflib.NewSfga()
	if err := arc.Create(workDir); err != nil {
		return nil, err
	}

	if _, err := arc.Connect(); err != nil {
		return nil, err
	}

	return arc, nil
}

// prepareWorkDir creates a fresh, empty work directory for a single source
// under ~/.cache/gndb/export/{sourceID}/. Any previous contents are cleared.
func prepareWorkDir(homeDir string, sourceID int) (string, error) {
	base := config.CacheDir(homeDir)
	dir := filepath.Join(base, "export", fmt.Sprintf("%d", sourceID))

	if err := os.RemoveAll(dir); err != nil {
		return "", WorkDirError(sourceID, err)
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", WorkDirError(sourceID, err)
	}

	return dir, nil
}

// buildOutputBase returns the base output path (without extension) for a
// data source, following the SFGA naming convention:
//
//	{outputDir}/{ID:04d}-{title_short_slug}-{date}
//
// Date comes from RevisionDate, falling back to UpdatedAt.
func buildOutputBase(ds schema.DataSource, outputDir string) string {
	date := ds.RevisionDate
	if date == "" {
		date = ds.UpdatedAt.Format("2006-01-02")
	}

	// Guard against still-empty date (zero UpdatedAt).
	if date == "" || date == "0001-01-01" {
		date = time.Now().Format("2006-01-02")
	}

	slug := slugify(ds.TitleShort)
	if slug == "" {
		slug = "source"
	}

	name := fmt.Sprintf("%04d-%s-%s", ds.ID, slug, date)
	return filepath.Join(outputDir, name)
}

// slugify converts a title into a lowercase, hyphen-separated slug.
// Spaces become hyphens; non-alphanumeric characters are stripped.
func slugify(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, " ", "-")
	// Strip anything that isn't a letter, digit or hyphen.
	re := regexp.MustCompile(`[^a-z0-9\-]`)
	s = re.ReplaceAllString(s, "")
	// Collapse multiple consecutive hyphens.
	re2 := regexp.MustCompile(`-{2,}`)
	s = re2.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// dataSourceToConfig converts a schema.DataSource to a sources.DataSourceConfig
// suitable for writing to a sources.yaml-compatible file.
// parent is the value for the `parent` field (serving URL or directory).
func dataSourceToConfig(ds schema.DataSource, parent string) sources.DataSourceConfig {
	src := sources.DataSourceConfig{
		ID:                ds.ID,
		Parent:            parent,
		Title:             ds.Title,
		TitleShort:        ds.TitleShort,
		Description:       ds.Description,
		HomeURL:           ds.WebsiteURL,
		DataURL:           ds.DataURL,
		IsCurated:         ds.IsCurated,
		IsAutoCurated:     ds.IsAutoCurated,
		HasClassification: ds.HasTaxonData,
		IsOutlinkReady:    ds.IsOutlinkReady,
		OutlinkURL:        ds.OutlinkURL,
	}

	// When an outlink URL is present, set outlink_id_column to the standard
	// column where gndb stores outlink IDs during export.
	if ds.OutlinkURL != "" {
		src.OutlinkIDColumn = "name.col__alternative_id"
	}

	return src
}

// writeCompanionYAML writes a single sources.yaml-compatible entry alongside
// the exported SFGA files for one data source. Placed at {basePath}.yaml.
//
// The `parent` field is set to cfg.Export.ParentDir, falling back to
// cfg.Export.OutputDir — reflecting where the files will actually be served.
func writeCompanionYAML(
	ds schema.DataSource,
	basePath string,
	cfg *config.Config,
) error {
	parent := cfg.Export.ParentDir
	if parent == "" {
		parent = cfg.Export.OutputDir
	}

	date := ds.RevisionDate
	if date == "" {
		date = ds.UpdatedAt.Format("2006-01-02")
	}

	header := fmt.Sprintf(
		"# Generated by gndb export on %s\n"+
			"# Add this entry to your sources.yaml or custom_sources.yaml to re-import.\n",
		date,
	)

	data, err := yaml.Marshal(dataSourceToConfig(ds, parent))
	if err != nil {
		return CompanionYAMLError(basePath+".yaml", err)
	}

	yamlPath := basePath + ".yaml"
	content := append([]byte(header), data...)

	if err := os.WriteFile(yamlPath, content, 0644); err != nil {
		return CompanionYAMLError(yamlPath, err)
	}

	slog.Info("Wrote companion YAML", "path", yamlPath)
	return nil
}

// writeConsolidatedYAML writes a single sources-export.yaml in the output
// directory listing all successfully exported sources. It is a valid
// sources.yaml that users can drop into ~/.config/gndb/ or append to their
// existing sources.yaml to re-import all exported sources at once.
//
// Written after all per-source exports complete; only includes sources that
// exported successfully (caller passes only the successful ones).
func writeConsolidatedYAML(
	exported []schema.DataSource,
	cfg *config.Config,
) error {
	if len(exported) == 0 {
		return nil
	}

	parent := cfg.Export.ParentDir
	if parent == "" {
		parent = cfg.Export.OutputDir
	}

	var cfgs []sources.DataSourceConfig
	for _, ds := range exported {
		cfgs = append(cfgs, dataSourceToConfig(ds, parent))
	}

	sc := sources.SourcesConfig{DataSources: cfgs}

	header := fmt.Sprintf(
		"# Generated by gndb export on %s\n"+
			"# Contains %d data source(s).\n"+
			"# Copy to ~/.config/gndb/sources.yaml or append entries to your existing file.\n",
		time.Now().Format("2006-01-02"),
		len(exported),
	)

	data, err := yaml.Marshal(sc)
	if err != nil {
		return CompanionYAMLError("sources-export.yaml", err)
	}

	yamlPath := filepath.Join(cfg.Export.OutputDir, "sources-export.yaml")
	content := append([]byte(header), data...)

	if err := os.WriteFile(yamlPath, content, 0644); err != nil {
		return CompanionYAMLError(yamlPath, err)
	}

	slog.Info("Wrote consolidated YAML",
		"path", yamlPath,
		"sources", len(exported),
	)
	return nil
}
